//
//  MeetupEventListModels.swift
//  ITApp
//
//  Created by Chiaote Ni on 2020/10/28.
//  Copyright (c) 2020 iOS@Taipei in iPlayground. All rights reserved.
//
//  This file was generated by iOS@Taipei's Clean Architecture Xcode Templates, which
//  is goaled to help you apply clean architecture to your iOS projects,
//

import UIKit

enum MeetupEventList {
    
    typealias EventResponseItem = (meetupEvent: MeetupEvent, favoriteState: MeetupEventFavoriteState)
    
    // MARK: - Models
    
    struct DisplayRecentlyEvent {
        let id: String
        let title: String
        let dateText: String
        let hostName: String
        let coverImageURL: URL?
    }
    
    struct DisplayHistoryEvent {
        let id: String
        let title: String
        let dateText: String
        let hostName: String
        let coverImageURL: URL?
        let favoriteButtonColor: UIColor
    }

    // MARK: - Use cases

    enum FetchEvents {
        struct Request { }

        struct Response {
            let recentlyEvents: [EventResponseItem]
            let historyEvents: [EventResponseItem]
        }

        struct ViewModel {
            let historyEvents: [DisplayHistoryEvent]
            let recentlyEvents: [DisplayRecentlyEvent]
        }
    }
    
    enum TapFavorite {
        struct Request {
            let meetupEventID: String
        }
    }
    
    enum SubscribeFavoriteUpdate {
        struct Request {}
    }
    
    enum UnsubscribeFavoriteUpdate {
        struct Request {}
    }
    
    enum UpdateHistoryEvent {
        
        struct Response {
            let targetEvent: EventResponseItem
        }

        struct ViewModel {
            let targetEvent: DisplayHistoryEvent
        }
    }
}
